---
title: "Imbalanced Classification Tasks"
author: "Ignacio Vellido Expósito"
date: "18/01/2021"
output:
  prettydoc::html_pretty:
    theme: hpstr
    highlight: github
    df_print: paged
---

```{r setup, include=FALSE}
# Configuración RMarkdown
knitr::opts_chunk$set(echo = TRUE, results="hold", fig.align="center", 
                      comment=NA, messages=FALSE)
# Librerías
library(tidyverse)
library(tree)
```


```{r}
# Leer datos
df <- read_csv("data/esl.arff", col_names = FALSE, skip = 43)

# Cada columna es categórica ordinal
for (i in 1:(ncol(df)-1)) {
  df[[i]] <- df[[i]] %>% as.factor()
}

df
```

```{r}
# Añadir nombre de columna a las etiquetas
colnames(df)[5] <- "labels"
df
```


```{r}
# Ordenar df por etiquetas
df <- df %>% arrange(labels)
df
```


```{r}
# Realizar particiones
labels <- as.integer(unique(df$labels))
num_part <- length(labels) - 1

partitions <- vector("list", length(num_part))

for(i in 1:num_part) {
  partitions[[i]] <- df
  partitions[[i]] <- partitions[[i]] %>% mutate(labels = ifelse(labels <= i, 0, 1))
}

partitions
```

```{r}
# Clasificar
models <- vector("list", length(num_part))
for (i in 1:num_part) {
    models[[i]] <- tree(labels ~ ., data = partitions[[i]])
}
# models
```


```{r}
# Obtener probabilidades de cada fila para cada modelo
probabilities <- lapply(models, predict, df %>% head())
probabilities %>% lapply(print)
print("------------------")
probabilities
```

```{r}
# Calcular probabilidades del df para un modelo
b <- lapply(models, function(x,y) {
  predict(x, y) %>% as.data.frame() -> a
  print(a)
  a %>% mutate(row = rownames(a))
}, df %>% head(2))

# Juntar probabilidades por filas del df
b <- reduce(b, left_join, by="row")

b
```


```{r}
# Mover la columna auxiliar row a la primera posición
# y llenarla con unos, preparando el cálculo de las
# probabilidades de cada clase
b <- b[, c(2,1,3:ncol(b))]
b$row <- 1
b
```

```{r}
# Calcular probabilidades de cada clase
apply(b %>% head(2), 1, function(row) {
  probs <- vector("integer", length(row-1))
  for(i in 2:length(row)) {
    probs[i-1] <- row[[i-1]] * (1 - row[[i]])
    # print(row[[i]])
  }
  
  # Devolver el máximo (y el índice)
  m  <- max(probs)
  data.frame(class=which(probs == m), prob = m)
}) %>% reduce(bind_rows)
```


```{r}
classify <- function(df) {
    # Realizar particiones
    labels <- as.integer(unique(df$labels))
    num_part <- length(labels) - 1
    
    partitions <- vector("list", length(num_part))
    
    for(i in 1:num_part) {
      partitions[[i]] <- df
      partitions[[i]] <- partitions[[i]] %>% mutate(labels = ifelse(labels <= i, 0, 1))
      
      # Para realizar el entrenamiento, necesitamos que las etiquetas se codifiquen
      # como factores
      partitions[[i]]$labels <- partitions[[i]]$labels %>% as.factor()
    }

    # Clasificar
    models <- vector("list", length(num_part))
    for (i in 1:num_part) {
        models[[i]] <- tree(labels ~ ., data = partitions[[i]])
    }

    # Devolver modelos
    models
}
```

```{r}
make_predictions <- function(models, df) {
    # Calcular probabilidades del df para un modelo
    pr_list <- lapply(models,
                function(m,r) {
                  # Solo nos interesa la segunda probabilidad, que sea > i
                  predict(m,r)[,2] %>% as.data.frame() -> x
                  x %>% mutate(row = rownames(x))
                },
                df)
    
    
    # Juntar probabilidades por filas del df
    pr_list <- reduce(pr_list, left_join, by="row")
    

    # Mover la columna auxiliar row a la primera posición
    # y llenarla con unos, preparando el cálculo de las
    # probabilidades de cada clase
    pr_list <- pr_list[, c(2,1,3:ncol(pr_list))]
    pr_list$row <- 1
    

    # Calcular probabilidades reales de cada clase
    apply(pr_list, 1, function(row) {
      probs <- vector("integer", length(row))

      for(i in 2:length(row)) {
        probs[i-1] <- row[[i-1]] * (1 - row[[i]])
      }
      
      # Probabilidad última clase
      probs[length(row)] <- row[[length(row)]]

      # Devolver probabilidad máxima (y el índice)
      m  <- max(probs)
      data.frame(class=which(probs == m), prob = m)
    }) %>%
      reduce(bind_rows) # Juntar en un solo dataframe
}
```


```{r}
models <- classify(df)
make_predictions(models, df %>% select(-labels))

df %>% head()
```